export const ActionTypes = {
  STARSHIPS_GET: 'STARSHIPS_GET',
  STARSHIPS_GET_SUCCESS: 'STARSHIPS_GET_SUCCESS',
  STARSHIPS_GET_FAILURE: 'STARSHIPS_GET_FAILURE',
  STARSHIP_GET_DETAIL: 'STARSHIP_GET_DETAIL',
  STARSHIP_GET_DETAIL_SUCCESS: 'STARSHIP_GET_DETAIL_SUCCESS',
  STARSHIP_GET_DETAIL_FAILURE: 'STARSHIP_GET_DETAIL_FAILURE',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_PAGE_SUCCESS: 'CHANGE_PAGE_SUCCESS',
  CHANGE_PAGE_FAILURE: 'CHANGE_PAGE_FAILURE',
};